function getStaticCoinData() {
    let coins_data = [
        { id: 'bitcoin', name: 'Bitcoin', symbol: 'BTC' },
        { id: 'ethereum', name: 'Ethereum', symbol: 'ETH' },
        { id: 'tether', name: 'Tether', symbol: 'USDT' },
        { id: 'binance-coin', name: 'BNB', symbol: 'BNB' },
        { id: 'usd-coin', name: 'USD Coin', symbol: 'USDC' },
        { id: 'ripple', name: 'XRP', symbol: 'XRP' },
        { id: 'staked-ether', name: 'Lido Staked Ether', symbol: 'STETH' },
        { id: 'cardano', name: 'Cardano', symbol: 'ADA' },
        { id: 'dogecoin', name: 'Dogecoin', symbol: 'DOGE' },
        { id: 'solana', name: 'Solana', symbol: 'SOL' },
        { id: 'tron', name: 'TRON', symbol: 'TRX' },
        { id: 'matic-network', name: 'Polygon', symbol: 'MATIC' },
        { id: 'litecoin', name: 'Litecoin', symbol: 'LTC' },
        { id: 'polkadot', name: 'Polkadot', symbol: 'DOT' },
        { id: 'shiba-inu', name: 'Shiba Inu', symbol: 'SHIB' },
        { id: 'wrapped-bitcoin', name: 'Wrapped Bitcoin', symbol: 'WBTC' },
        { id: 'avalanche-2', name: 'Avalanche', symbol: 'AVAX' },
        { id: 'dai', name: 'Dai', symbol: 'DAI' },
        { id: 'binance-usd', name: 'Binance USD', symbol: 'BUSD' },
        { id: 'uniswap', name: 'Uniswap', symbol: 'UNI' },
        { id: 'trueusd', name: 'TrueUSD', symbol: 'TUSD' },
        { id: 'chainlink', name: 'Chainlink', symbol: 'LINK' },
        { id: 'cosmos', name: 'Cosmos Hub', symbol: 'ATOM' },
        { id: 'bitcoin-cash', name: 'Bitcoin Cash', symbol: 'BCH' },
        { id: 'monero', name: 'Monero', symbol: 'XMR' },
        { id: 'ethereum-classic', name: 'Ethereum Classic', symbol: 'ETC' },
        { id: 'stellar', name: 'Stellar', symbol: 'XLM' },
        { id: 'the-open-network', name: 'Toncoin', symbol: 'TON' },
        { id: 'internet-computer', name: 'Internet Computer', symbol: 'ICP' },
        { id: 'lido-dao', name: 'Lido DAO', symbol: 'LDO' },
        { id: 'filecoin', name: 'Filecoin', symbol: 'FIL' },
        { id: 'hedera-hashgraph', name: 'Hedera', symbol: 'HBAR' },
        { id: 'aptos', name: 'Aptos', symbol: 'APT' },
        { id: 'quant', name: 'Quant', symbol: 'QNT' },
        { id: 'crypto-com-chain', name: 'Cronos', symbol: 'CRO' },
        { id: 'ethos', name: 'Voyager VGX', symbol: 'VGX' },
        { id: 'arbitrum', name: 'Arbitrum', symbol: 'ARB' },
        { id: 'compound-wrapped-btc', name: 'cWBTC', symbol: 'CWBTC' },
        { id: 'near', name: 'NEAR Protocol', symbol: 'NEAR' },
        { id: 'vechain', name: 'VeChain', symbol: 'VET' },
        { id: 'blockstack', name: 'Stacks', symbol: 'STX' },
        { id: 'the-graph', name: 'The Graph', symbol: 'GRT' },
        { id: 'frax', name: 'Frax', symbol: 'FRAX' },
        { id: 'paxos-standard-token', name: 'Pax Dollar', symbol: 'USDP' },
        { id: 'rocket-pool-eth', name: 'Rocket Pool ETH', symbol: 'RETH' },
        { id: 'optimism', name: 'Optimism', symbol: 'OP' },
        { id: 'algorand', name: 'Algorand', symbol: 'ALGO' },
        { id: 'apecoin', name: 'ApeCoin', symbol: 'APE' },
        { id: 'render-token', name: 'Render', symbol: 'RNDR' },
        { id: 'fantom', name: 'Fantom', symbol: 'FTM' },
        { id: 'elrond-erd-2', name: 'MultiversX', symbol: 'EGLD' },
        { id: 'aave', name: 'Aave', symbol: 'AAVE' },
        { id: 'rocket-pool', name: 'Rocket Pool', symbol: 'RPL' },
        { id: 'the-sandbox', name: 'The Sandbox', symbol: 'SAND' },
        { id: 'eos', name: 'EOS', symbol: 'EOS' },
        { id: 'immutable-x', name: 'ImmutableX', symbol: 'IMX' },
        { id: 'tezos', name: 'Tezos', symbol: 'XTZ' },
        { id: 'usdd', name: 'USDD', symbol: 'USDD' },
        { id: 'theta-token', name: 'Theta Network', symbol: 'THETA' },
        { id: 'whitebit', name: 'WhiteBIT Token', symbol: 'WBT' },
        { id: 'decentraland', name: 'Decentraland', symbol: 'MANA' },
        { id: 'bitget-token', name: 'Bitget Token', symbol: 'BGB' },
        { id: 'radix', name: 'Radix', symbol: 'XRD' },
        { id: 'maker', name: 'Maker', symbol: 'MKR' },
        { id: 'kucoin-shares', name: 'KuCoin', symbol: 'KCS' },
        { id: 'gala', name: 'GALA', symbol: 'GALA' },
        { id: 'neo', name: 'NEO', symbol: 'NEO' },
        { id: 'axie-infinity', name: 'Axie Infinity', symbol: 'AXS' },
        { id: 'pepe', name: 'Pepe', symbol: 'PEPE' },
        { id: 'havven', name: 'Synthetix Network', symbol: 'SNX' },
        { id: 'bitdao', name: 'BitDAO', symbol: 'BIT' },
        { id: 'flow', name: 'Flow', symbol: 'FLOW' },
        { id: 'curve-dao-token', name: 'Curve DAO', symbol: 'CRV' },
        { id: 'gatechain-token', name: 'Gate', symbol: 'GT' },
        { id: 'injective-protocol', name: 'Injective', symbol: 'INJ' },
        { id: 'gemini-dollar', name: 'Gemini Dollar', symbol: 'GUSD' },
        { id: 'kava', name: 'Kava', symbol: 'KAVA' },
        { id: 'bitcoin-sv', name: 'Bitcoin SV', symbol: 'BSV' },
        { id: 'terra-luna', name: 'Terra Luna Classic', symbol: 'LUNC' },
        { id: 'bitmax', name: 'BMAX', symbol: 'BMAX' },
        { id: 'klay-token', name: 'Klaytn', symbol: 'KLAY' },
        { id: 'conflux-token', name: 'Conflux', symbol: 'CFX' },
        { id: 'compound-ether', name: 'cETH', symbol: 'CETH' },
        { id: 'gmx', name: 'GMX', symbol: 'GMX' },
        { id: 'pax-gold', name: 'PAX Gold', symbol: 'PAXG' },
        { id: 'iota', name: 'IOTA', symbol: 'MIOTA' },
        { id: 'tokenize-xchange', name: 'Tokenize Xchange', symbol: 'TKX' },
        { id: 'tether-gold', name: 'Tether Gold', symbol: 'XAUT' },
        { id: 'kaspa', name: 'Kaspa', symbol: 'KAS' },
        { id: 'casper-network', name: 'Casper Network', symbol: 'CSPR' },
        { id: 'bittorrent-2', name: 'BitTorrent', symbol: 'BTT' },
        { id: 'xinfin-network', name: 'XDC Network', symbol: 'XDC' },
        { id: 'sui', name: 'Sui', symbol: 'SUI' },
        { id: 'mina-protocol', name: 'Mina Protocol', symbol: 'MINA' },
        { id: 'ecash', name: 'eCash', symbol: 'XEC' },
        { id: 'frax-share', name: 'Frax Share', symbol: 'FXS' },
        { id: 'frax-ether', name: 'Frax Ether', symbol: 'FRXETH' },
        { id: 'huobi-token', name: 'Huobi', symbol: 'HT' },
        { id: 'chiliz', name: 'Chiliz', symbol: 'CHZ' },
        { id: 'trust-wallet-token', name: 'Trust Wallet', symbol: 'TWT' },
        { id: 'dash', name: 'Dash', symbol: 'DASH' },
        { id: 'compound-usd-coin', name: 'cUSDC', symbol: 'CUSDC' },
        { id: 'woo-network', name: 'WOO Network', symbol: 'WOO' },
        { id: 'nxm', name: 'Nexus Mutual', symbol: 'NXM' },
        { id: 'nexo', name: 'NEXO', symbol: 'NEXO' },
        { id: 'arweave', name: 'Arweave', symbol: 'AR' },
        { id: 'mask-network', name: 'Mask Network', symbol: 'MASK' },
        { id: 'zilliqa', name: 'Zilliqa', symbol: 'ZIL' },
        { id: 'okb', name: 'OKB', symbol: 'OKB' },
        { id: 'dydx', name: 'dYdX', symbol: 'DYDX' },
        { id: 'tominet', name: 'tomiNet', symbol: 'TOMI' },
        { id: 'osmosis', name: 'Osmosis', symbol: 'OSMO' },
        { id: 'convex-finance', name: 'Convex Finance', symbol: 'CVX' },
        { id: 'pancakeswap-token', name: 'PancakeSwap', symbol: 'CAKE' },
        { id: 'gnosis-gno', name: 'Gnosis', symbol: 'GNO' },
        { id: 'singularitynet', name: 'SingularityNET', symbol: 'AGIX' },
        { id: 'flare-networks', name: 'Flare', symbol: 'FLR' },
        { id: '1inch', name: '1inch', symbol: '1INCH' },
        { id: 'loopring', name: 'Loopring', symbol: 'LRC' },
        { id: 'enjin-coin', name: 'Enjin Coin', symbol: 'ENJ' },
        { id: 'oec-token', name: 'OKT Chain', symbol: 'OKT' },
        { id: 'beldex', name: 'Beldex', symbol: 'BDX' },
        { id: 'thorchain', name: 'THORChain', symbol: 'RUNE' },
        { id: 'basic-attention-token', name: 'Basic Attention', symbol: 'BAT' },
        { id: 'mx-token', name: 'MX', symbol: 'MX' },
        { id: 'liquity-usd', name: 'Liquity USD', symbol: 'LUSD' },
        { id: 'flex-coin', name: 'FLEX Coin', symbol: 'FLEX' },
        {
            id: 'staked-frax-ether',
            name: 'Staked Frax Ether',
            symbol: 'SFRXETH'
        },
        { id: 'blur', name: 'Blur', symbol: 'BLUR' },
        { id: 'huobi-btc', name: 'Huobi BTC', symbol: 'HBTC' },
        { id: 'gaj', name: 'Gaj Finance', symbol: 'GAJ' },
        { id: 'illuvium', name: 'Illuvium', symbol: 'ILV' },
        { id: 'floki-inu', name: 'FLOKI', symbol: 'FLOKI' },
        { id: 'oasis-network', name: 'Oasis Network', symbol: 'ROSE' },
        { id: 'defichain', name: 'DeFiChain', symbol: 'DFI' },
        { id: 'chia', name: 'Chia', symbol: 'XCH' },
        { id: 'cdai', name: 'cDAI', symbol: 'CDAI' },
        { id: 'fetch-ai', name: 'Fetch.ai', symbol: 'FET' },
        { id: 'nem', name: 'NEM', symbol: 'XEM' },
        { id: 'holo', name: 'Holo', symbol: 'HOT' },
        { id: 'qtum', name: 'Qtum', symbol: 'QTUM' },
        { id: 'baby-doge-coin', name: 'Baby Doge Coin', symbol: 'BABYDOGE' },
        { id: 'zcash', name: 'Zcash', symbol: 'ZEC' },
        { id: 'theta-fuel', name: 'Theta Fuel', symbol: 'TFUEL' },
        { id: 'celo', name: 'Celo', symbol: 'CELO' },
        { id: 'escoin-token', name: 'Escoin', symbol: 'ELG' },
        { id: 'aleph-zero', name: 'Aleph Zero', symbol: 'AZERO' },
        { id: 'tether-eurt', name: 'Euro Tether', symbol: 'EURT' },
        { id: 'ravencoin', name: 'Ravencoin', symbol: 'RVN' },
        { id: 'bitcoin-gold', name: 'Bitcoin Gold', symbol: 'BTG' },
        { id: 'swipe', name: 'SXP', symbol: 'SXP' },
        { id: 'decred', name: 'Decred', symbol: 'DCR' },
        {
            id: 'ethereum-name-service',
            name: 'Ethereum Name Service',
            symbol: 'ENS'
        },
        { id: 'kusama', name: 'Kusama', symbol: 'KSM' },
        { id: 'link', name: 'FINSCHIA', symbol: 'FNSA' },
        { id: 'yearn-finance', name: 'yearn.finance', symbol: 'YFI' },
        { id: 'ethereum-pow-iou', name: 'EthereumPoW', symbol: 'ETHW' },
        { id: 'ronin', name: 'Ronin', symbol: 'RON' },
        { id: 'jasmycoin', name: 'JasmyCoin', symbol: 'JASMY' },
        { id: 'compound-governance-token', name: 'Compound', symbol: 'COMP' },
        { id: 'icon', name: 'ICON', symbol: 'ICX' },
        { id: 'astar', name: 'Astar', symbol: 'ASTR' },
        { id: 'balancer', name: 'Balancer', symbol: 'BAL' },
        { id: 'convex-crv', name: 'Convex CRV', symbol: 'CVXCRV' },
        { id: 'audius', name: 'Audius', symbol: 'AUDIO' },
        { id: 'olympus', name: 'Olympus', symbol: 'OHM' },
        { id: 'btse-token', name: 'BTSE Token', symbol: 'BTSE' },
        { id: 'just', name: 'JUST', symbol: 'JST' },
        { id: 'bone-shibaswap', name: 'Bone ShibaSwap', symbol: 'BONE' },
        { id: 'terra-luna-2', name: 'Terra', symbol: 'LUNA' },
        { id: 'iotex', name: 'IoTeX', symbol: 'IOTX' },
        { id: 'ankr', name: 'Ankr Network', symbol: 'ANKR' },
        { id: 'helium_hnt', name: 'Helium', symbol: 'HNT' },
        { id: 'magic', name: 'Magic', symbol: 'MAGIC' },
        {
            id: 'eth_frax3crv-f_0xd632f22692fac7611d2aa1c0d552930d43caed3b',
            name: 'Curve.fi Factory USD Metapool: Frax',
            symbol: 'FRAX3CRV-f'
        },
        { id: 'golem-network-tokens', name: 'Golem', symbol: 'GLM' },
        {
            id: 'eth_fsohm-18_0x6eda4b59bac787933a4a21b65672539cef6ec97b',
            name: 'Olympus Pool Party Staked Olympus',
            symbol: 'fsOHM-18'
        },
        {
            id: 'bitcoin-avalanche-bridged-btc-b',
            name: 'Bitcoin Avalanche Bridged (BTC.b)',
            symbol: 'BTC.B'
        },
        { id: 'safepal', name: 'SafePal', symbol: 'SFP' },
        { id: 'aragon', name: 'Aragon', symbol: 'ANT' },
        { id: 'moonbeam', name: 'Moonbeam', symbol: 'GLMR' },
        {
            id: 'eth_3crvcrypto2_0xc4ad29ba4b3c580e6d59105fff484999997675ff',
            name: 'Curve Tricrypto Pool',
            symbol: '3CrvCrypto2'
        },
        { id: 'wemix-token', name: 'WEMIX', symbol: 'WEMIX' },
        { id: 'alchemix-usd', name: 'Alchemix USD', symbol: 'ALUSD' },
        { id: '0x', name: '0x Protocol', symbol: 'ZRX' },
        { id: 'ordinals', name: 'ORDI', symbol: 'ORDI' },
        { id: 'ontology', name: 'Ontology', symbol: 'ONT' },
        { id: 'gains-farm', name: 'Gains Farm', symbol: 'GFARM2' },
        { id: 'lukso-token', name: 'LUKSO', symbol: 'LYXE' },
        { id: 'ecomi', name: 'ECOMI', symbol: 'OMI' },
        { id: 'blox', name: 'Blox', symbol: 'CDT' },
        { id: 'iostoken', name: 'IOST', symbol: 'IOST' },
        { id: 'harmony', name: 'Harmony', symbol: 'ONE' },
        { id: 'wax', name: 'WAX', symbol: 'WAXP' },
        { id: 'siacoin', name: 'Siacoin', symbol: 'SC' },
        { id: 'ocean-protocol', name: 'Ocean Protocol', symbol: 'OCEAN' },
        { id: 'band-protocol', name: 'Band Protocol', symbol: 'BAND' },
        { id: 'waves', name: 'Waves', symbol: 'WAVES' },
        { id: 'kadena', name: 'Kadena', symbol: 'KDA' },
        { id: 'seth2', name: 'sETH2', symbol: 'SETH2' },
    ];
    return coins_data
}

function staticExchangePlatform() {
    return [
        "ABCC",
        "AidosMarket",
        "AltcoinTrader",
        "Ataix",
        "BTCAlpha",
        "BTCMarkets",
        "BTCTradeUA",
        "BW",
        "BalancerV1",
        "Bancor",
        "Beaxy",
        "Bibox",
        "BigOne",
        "Bilaxy",
        "Binance",
        "BinanceDex",
        "BinanceFutures",
        "BinanceUS",
        "Bit2C",
        "BitForex",
        "BitMEX",
        "BitMart",
        "BitMax",
        "Bitbank",
        "Bitblinx",
        "Bitbns",
        "Bitbuy",
        "BitcoinTrade",
        "Bitfinex",
        "Bitget",
        "Bithesap",
        "Bithumb",
        "BithumbGlobal",
        "Bitkub",
        "Bitopro",
        "Bitpanda Pro",
        "Bitrue",
        "Bitso",
        "Bitstamp",
        "Bittrex",
        "Bkex",
        "Bleutrade",
        "Bololex",
        "Btcturk",
        "Btse",
        "Bybit",
        "CEX.IO",
        "COSS",
        "Cashierest",
        "CatEx",
        "Chainex",
        "CoinCorner",
        "CoinEgg",
        "CoinEx",
        "CoinFalcon",
        "CoinFlex",
        "CoinJar",
        "CoinMate",
        "CoinSpot",
        "CoinTiger",
        "Coinbase",
        "Coincheck",
        "Coingi",
        "Coinone",
        "Coinsbit",
        "Crex24",
        "Crypto.com",
        "CryptoMKT",
        "Cryptology",
        "Cryptonex",
        "Currency.com",
        "DDEX",
        "Deribit",
        "DigiFinex",
        "ExMarkets",
        "Exmo",
        "FinexBox",
        "Fmfw",
        "FreiExchange",
        "GDAX",
        "GOPAX",
        "Gate.io",
        "Gemini",
        "Gokumarket",
        "Graviex",
        "HitBTC",
        "Hotbit",
        "HuobiPro",
        "IDEX",
        "IndependentReserve",
        "Indodax",
        "InfinityCoin",
        "Koinim",
        "Kraken",
        "Kucoin",
        "KucoinFutures",
        "Kuna",
        "LBank",
        "Latoken",
        "Lcx",
        "Liquid",
        "LiteBit",
        "LocalBitcoins",
        "Luno",
        "Lykke",
        "Maicoin",
        "MercadoBitcoin",
        "Mercatox",
        "Mexc",
        "Narkasa",
        "NovaDAX",
        "OKCoin",
        "OKEX",
        "OKEXFutures",
        "Oceanex",
        "OpenOcean",
        "P2PB2B",
        "PancakeSwapV2",
        "Paribu",
        "Paymium",
        "Poloniex",
        "Probit",
        "SIGEN.pro",
        "STEX",
        "SatoExchange",
        "SecondBTC",
        "Simex",
        "SouthXchange",
        "StellarTerm",
        "Sushiswap",
        "TheRockTrading",
        "Tidex",
        "Tokenomy",
        "UniswapV2",
        "UniswapV3",
        "UpHold",
        "Upbit",
        "Vindax",
        "Waves Exchange",
        "WazirX",
        "Whitebit",
        "Xt",
        "Yobit",
        "ZBCom",
        "Zaif",
        "itBit"
    ]
}

module.exports = {
    getStaticCoinData,
    staticExchangePlatform
}